# Generated by Django 4.0.3 on 2022-04-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_Accountant',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('pan_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tax_Admin',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('pan_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tax_Payer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('gst_number', models.CharField(max_length=15)),
                ('pan_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgst', models.CharField(max_length=10)),
                ('cgst', models.CharField(max_length=10)),
                ('ugst', models.CharField(max_length=10, null=True)),
                ('arrears', models.CharField(max_length=10, null=True)),
                ('fines', models.CharField(max_length=10, null=True)),
                ('income', models.CharField(max_length=10)),
                ('texable_amount', models.CharField(max_length=10)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tax_payer')),
            ],
        ),
    ]
